targets:
  $default:
    builders:
      fontresoft|font_style:
        generate_for:
          - lib/src/fontresoft.dart

builders:
  fontresoft|font_style:
    import: "package:fontresoft/build.dart"
    builder_factories: [ "fontStyleBuilder" ]
    build_extensions: { ".dart": [ ".fontresoft.g.dart" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]
